### PR TITLE
Tech 7285 upgrade ruby and bundler

### PR DESCRIPTION
**Pull request by dcaddell**
## Summary of Changes
- Use ruby 2.7
- Bundle with bundler 2
- Upgrade to rails 5 and remove rails 4 support
- Fix shoulda configuration to work with rails 5/6

### CODE REVIEW

**Review by yinonrousso — APPROVED** [review]
LGTM! Nice work getting the shoulda gem configured appropriately 👍

**Comment by yinonrousso** [comment]
Just noticed this is a public repository. Do we want to move this pipeline over to github actions?

**Review by jebentier — APPROVED** [review]
Nice work! This looks great. Yinon makes a good point that we should switch this off of buildkite. Feel free to skip that and merge these changes and we can do a separate ticket to move this build to Actions.

**Comment by dcaddell** [comment]
Nice catch again @yinonrousso :) I'll leave a note on the spreadsheet to circle back to this

**Pull request merged**
